[project]
name = "otus-hw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pylint==3.3.5",
    "pytest==8.3.5",
    "sqlalchemy==2.0.39",
]
